# Generated by Django 3.2.9 on 2021-12-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211208_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='street1',
        ),
    ]
