# Generated by Django 3.2.9 on 2021-12-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=20)),
                ('street', models.CharField(blank=True, max_length=30)),
                ('street1', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('c1', 'C1'), ('c2', 'C2'), ('c3', 'C3')], default='c1', max_length=20)),
            ],
        ),
    ]
