# Generated by Django 3.2.9 on 2021-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='street1',
        ),
        migrations.AddField(
            model_name='application',
            name='zip_code',
            field=models.CharField(default='452001', max_length=6),
        ),
    ]
